### ISSUE TITLE
[Feat] 매장 찾기 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#14]
## ✅ Description

매장 찾기 화면 구성

## ✔️ TODO
- [ ] 매장 찾기 - 지도 화면 구성
- [ ] 매장 찾기 - 리스트 화면 구성
- [ ] 매장 찾기 검색 화면 구성
- [ ] 매장 찾기 검색 결과 - 지도 화면 구성
- [ ] 매장 찾기 검색 결과 - 리스트 화면 구성
- [ ] 매장 찾기 - 상세 페이지 화면 구성
