### ISSUE TITLE
[Feat] 그룹 생성 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#20]
## ✅ Description

그룹 생성 화면 구성

## ✔️ TODO
- [ ] 그룹 생성 - 그룹 유형 선택 화면 구성
- [ ] 그룹 생성 - 기본 정보 입력 화면 구성
- [ ] 그룹 생성 - 계좌번호 입력 화면 구성
- [ ] 그룹 생성 - 기본 정보 입력 화면 bottom sheet 구성
- [ ] 그룹 생성 - 그룹원 초대 화면 구성
- [ ] 그룹 생성 - 그룹원 초대 화면 bottom sheet 구성
- [ ] 그룹 생성 완료 화면 구성
