### ISSUE TITLE
[Feat] 선결제 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#22]
## ✅ Description

선결제 화면 구성

## ✔️ TODO
- [ ] 선결제 - 금액 입력 화면 구성
- [ ] 선결제 - 1인당 사용 가능 금액 설정 화면 구성
- [ ] 선결제 - 완료 화면 구성
