### ISSUE TITLE
[Feat] 그룹 API 연동

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#31]
## ✅ Description

그룹 API 연동

## ✔️ TODO
- [ ] 그룹 생성 API 연동
- [ ] 비밀코드를 통한 그룹 조회 API 연동
- [ ] 그룹 입장 API 연동
- [ ] 그룹 정보 가져오기 API 연동
