### ISSUE TITLE
[Feat] 내 그룹 화면 수정 및 API 연동

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#41]
## ✅ Description

내 그룹 화면 수정 및 API 연동

## ✔️ TODO
- [ ] 내 그룹 - 진행중 화면 수정
- [ ] 내 그룹 - 완료 화면 수정
- [ ] 내 그룹 상세 화면 구성
- [ ] 참여중인 멤버 확인 화면 구성
- [ ] 내 그룹 상세 - 매장 상세 화면 구성
- [ ] 내 그룹 상세 - 제휴 매장 전체 보기 화면 구성
- [ ] 내 전체 그룹 조회 API 연동
- [ ] 그룹원 목록 조회 API 연동
- [ ] 그룹 상세 조회 API 연동
