### ISSUE TITLE
[Feat] 메인 홈 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthon-univ/2024_DANPOONG_TEAM_5_FE_1#9]
## ✅ Description

메인 홈 화면 구성

## ✔️ TODO
- [ ] 메인 홈 화면 구성
- [ ] 첫 진입 사용자 - 장부 생성 바텀 시트 구성
- [ ] bottom navigation 구성
